### ISSUE TITLE
Title truncated

### ISSUE THREAD

**Issue by fabrix95** [tkuther/piwigo-bootstrap-darkroom#143]
Hi,

why does it truncate title if there is space?

![image](https://user-images.githubusercontent.com/27883759/35480920-8abed1ec-0419-11e8-8571-37a3805ee426.png)

**Comment by idbartosz** [comment]
Probably due to CSS rule like:
```css
.nav-breadcrumb > .nav-breadcrumb-item {
    max-width: 300px;
}
````
